### ISSUE TITLE
Documentar ¿Como escribo un post usando Jekyll?

### ISSUE THREAD

**Issue by juliosguz** [GDGCochabamba/gdgcochabamba.github.io#5]
Se tiene documentado como ser editor usando Jekyll pero la parte de como escribir un post, aun esta pendiente.

<img width="732" alt="screen shot 2016-12-19 at 11 14 20 am" src="https://cloud.githubusercontent.com/assets/896522/21317644/5eb76da6-c5dc-11e6-9e73-8fbc53021c65.png">

¿Quien se anima a documentarlo?

Pueden ver esa area de la wiki aquí: https://github.com/GDGCochabamba/gdgcochabamba.github.io/wiki/%C2%BFComo-puedo-ser-editor-del-blog%3F

**Comment by tokidev-ai** [comment]
Ya realise una pequeña documentación, me gustaría que alguien lo revise.

**Comment by juliosguz** [comment]
@whiletruedothis Yo creo que esta bien, le agregaras algo mas?

**Comment by tokidev-ai** [comment]
@juliosguz creo que no. Puse solo la sintaxis básica de markdown,  podría poner más pero no lo vi necesario. Crees que falta algo más por complementar?

**Comment by juliosguz** [comment]
@whiletruedothis todo esta ok, cerrare el issue, buen trabajo!
