### ISSUE TITLE
Agregar pagina "Preguntas frecuentes"

### ISSUE THREAD

**Issue by juliosguz** [GDGCochabamba/gdgcochabamba.github.io#9]
Seria bueno agregar la pagina preguntas frecuentes en el area del blog hasta que se decida si se puede mover al dominio principal.

Existe un post que hice el año pasado sobre eso, esa información la pondre aquí. Si alguien tiene otra sugerencia, comenten en este issue.

Post 2015:
https://www.facebook.com/groups/GDGCochabamba/permalink/1004522562911983/

**Comment by juliosguz** [comment]
@GDGCochabamba/blogteam  ¿le pueden dar una revisada ? https://github.com/GDGCochabamba/gdgcochabamba.github.io/commit/3740b80a5b8912ef16d17603599d5956b7d0ecec

**Comment by andresjordanze** [comment]
@juliosguz seria bueno agregar en la parte de "cómo ser parte activa" inbox a las páginas de Facebook ya sea GDG o WTM

**Comment by juliosguz** [comment]
@andresjordanze cierto, lo agregare xD

**Comment by juliosguz** [comment]
@GDGCochabamba/blogteam ¿Algo mas?
